# UHighlight - Configuration file
# More information : https://unturnedstore.com/products/

# # # # # # # # # # # # # # # # # # # # #
# 
#    Chat controls
#
# # # # # # #
#
# Icon used when the plugin sends chat messages
IconUrl: https://avatars.akamai.steamstatic.com/2739fbda6470073462a3c08fa638948762ac34de.jpg
#
# # # # # # #